// Code generated by Arduino IoT Cloud, DO NOT EDIT.

#include <ArduinoIoTCloud.h>
#include <Arduino_ConnectionHandler.h>

const char DEVICE_LOGIN_NAME[]  = "f19fdafa-2e2a-4bf0-922b-8ac23864ba25";

const char SSID[]               = SECRET_SSID;    // Network SSID (name)
const char PASS[]               = SECRET_OPTIONAL_PASS;    // Network password (use for WPA, or use as key for WEP)
const char DEVICE_KEY[]  = SECRET_DEVICE_KEY;    // Secret device password

void onWindspeedChange();
void onGestureChange();
void onOutputStatusChange();

float windspeed;
int gesture;
int outputStatus;

void initProperties(){

  ArduinoCloud.setBoardId(DEVICE_LOGIN_NAME);
  ArduinoCloud.setSecretDeviceKey(DEVICE_KEY);
  ArduinoCloud.addProperty(windspeed, READWRITE, ON_CHANGE, onWindspeedChange);
  ArduinoCloud.addProperty(gesture, READWRITE, ON_CHANGE, onGestureChange);
  ArduinoCloud.addProperty(outputStatus, READWRITE, ON_CHANGE, onOutputStatusChange);

}

WiFiConnectionHandler ArduinoIoTPreferredConnection(SSID, PASS);
